#index:
#    path: /
#    controller: App\Controller\DefaultController::index

2fa_login:
    path: /2fa
    defaults:
      _controller: App\Controller\SecurityController::check2fa
2fa_login_check:
    path: /2fa_check
